function accountStatus(msg,warn=false){const el=$('accountStatus');if(el){el.textContent=msg;el.classList.toggle('warn',warn)}setSaveStatus?.(msg)}
function fillCloudForm(){initSupabaseClient();if($('accountEmailInput'))$('accountEmailInput').value='';if($('accountPasswordInput'))$('accountPasswordInput').value='';updateAccountStatus()}
function updateAccountStatus(){if(!supabaseClient){accountStatus('尚未連線雲端；目前使用本機存檔。',true);refreshAccountCorner();return}accountStatus(currentUser?(cloudLockOwned?`已登入：${accountDisplayName()}｜這台裝置正在同步`:`已登入：${accountDisplayName()}｜目前為唯讀`):'尚未登入；可在右上角登入 / 註冊後自動同步。',!currentUser||!cloudLockOwned);refreshAccountCorner();refreshProfileAuthBlocks();updateProgressUI()}
function setAccountMode(mode='login'){accountMode=mode==='signup'?'signup':'login';if($('accountTitle'))$('accountTitle').textContent=accountMode==='login'?'登入帳號':'註冊帳號';if($('accountSubtitle'))$('accountSubtitle').textContent=accountMode==='login'?'登入後會自動載入雲端進度；不登入也可以使用本機存檔。':'建立帳號後會寄確認信；確認後回到遊戲登入。';if($('accountSubmitBtn'))$('accountSubmitBtn').textContent=accountMode==='login'?'登入':'註冊';if($('accountSwitchHint'))$('accountSwitchHint').textContent=accountMode==='login'?'還沒有帳號？點上方「註冊」。':'已經有帳號？點上方「登入」。';$('accountLoginTab')?.classList.toggle('primary',accountMode==='login');$('accountLoginTab')?.classList.toggle('secondary',accountMode!=='login');$('accountSignupTab')?.classList.toggle('primary',accountMode==='signup');$('accountSignupTab')?.classList.toggle('secondary',accountMode!=='signup')}
function showAccountScreen(mode='login'){if(currentUser){showProfileCenter();return}playSceneMusic('stageSelect');['start','levelScreen','game','characters','profile','shop'].forEach(id=>$(id)?.classList.remove('active'));$('accountScreen').classList.add('active');setAccountMode(mode);fillCloudForm()}
function submitAccountForm(){return accountMode==='signup'?signUpEmail():signInEmail()}
async function initAuth(){const client=initSupabaseClient();if(!client)return;const {data}=await client.auth.getSession();currentUser=data?.session?.user||null;client.auth.onAuthStateChange(async(event,session)=>{currentUser=session?.user||null;updateAccountStatus();if(event==='PASSWORD_RECOVERY'){showProfileCenter();accountStatus('驗證完成，請在「帳號與安全」設定新密碼。')}else if(currentUser)await pullCloudProfile(false)});updateAccountStatus();if(currentUser)await pullCloudProfile(false)}
async function signInEmail(){const client=initSupabaseClient();if(!client)return accountStatus('雲端尚未設定，無法登入。',true);const email=($('accountEmailInput')?.value||'').trim(),password=$('accountPasswordInput')?.value||'';if(!email||!password)return accountStatus('請輸入 Email 與密碼。',true);const {data,error}=await client.auth.signInWithPassword({email,password});if(error){accountStatus(error.message.toLowerCase().includes('confirm')?'登入失敗：請先到信箱點確認信，再回遊戲登入。':'登入失敗：'+error.message,true);return}currentUser=data.user;accountStatus('已登入，正在取得雲端資料與同步權限…');await pullCloudProfile(false);backToHome()}
async function signUpEmail(){const client=initSupabaseClient();if(!client)return accountStatus('雲端尚未設定，無法註冊。',true);const email=($('accountEmailInput')?.value||'').trim(),password=$('accountPasswordInput')?.value||'';if(!email||password.length<6)return accountStatus('請輸入 Email，密碼至少 6 位數。',true);const {data,error}=await client.auth.signUp({email,password,options:{emailRedirectTo:APP_URL}});if(error){accountStatus('註冊失敗：'+error.message,true);return}currentUser=data.session?.user||null;accountStatus(data.session?'註冊完成，已登入並準備同步。':'註冊完成，請到信箱點確認連結；確認後會回到遊戲頁面，再用 Email 登入。',!data.session);if(data.session){await claimCloudDevice(true);await pushCloudProfile(false);backToHome()}}
function showConfirm(title,message,confirmLabel='確認',danger=false){return new Promise(resolve=>{const box=$('confirmDialog'),yes=$('confirmDialogConfirm'),no=$('confirmDialogCancel');$('confirmDialogTitle').textContent=title;$('confirmDialogMessage').textContent=message;yes.textContent=confirmLabel;yes.classList.toggle('danger',danger);yes.classList.toggle('primary',!danger);const close=value=>{box.classList.remove('show');yes.onclick=null;no.onclick=null;document.removeEventListener('keydown',onKey);resolve(value)},onKey=e=>{if(e.key==='Escape')close(false)};yes.onclick=()=>close(true);no.onclick=()=>close(false);document.addEventListener('keydown',onKey);box.classList.add('show');no.focus()})}
async function requestPasswordReset(){const client=initSupabaseClient(),email=($('accountEmailInput')?.value||'').trim();if(!client||!email)return accountStatus('請先輸入要重設密碼的 Email。',true);const {error}=await client.auth.resetPasswordForEmail(email,{redirectTo:APP_URL});accountStatus(error?'重設信寄送失敗：'+error.message:'密碼重設信已寄出，請到信箱點連結。',!!error)}
async function resendConfirmation(){const client=initSupabaseClient(),email=($('accountEmailInput')?.value||'').trim();if(!client||!email)return accountStatus('請先輸入註冊 Email。',true);const {error}=await client.auth.resend({type:'signup',email,options:{emailRedirectTo:APP_URL}});accountStatus(error?'驗證信寄送失敗：'+error.message:'驗證信已重新寄出。',!!error)}
async function changeAccountPassword(){const value=$('profileNewPasswordInput')?.value||'';if(value.length<6)return setSaveStatus('新密碼至少需要 6 位數。');const {error}=await initSupabaseClient().auth.updateUser({password:value});if(!error)$('profileNewPasswordInput').value='';setSaveStatus(error?'密碼修改失敗：'+error.message:'密碼已修改。')}
async function changeAccountEmail(){const email=($('profileNewEmailInput')?.value||'').trim();if(!email)return setSaveStatus('請輸入新 Email。');const {error}=await initSupabaseClient().auth.updateUser({email},{emailRedirectTo:APP_URL});if(!error)$('profileNewEmailInput').value='';setSaveStatus(error?'Email 修改失敗：'+error.message:'確認信已寄到新 Email，完成確認後才會生效。')}
async function signInWithGoogle(){const client=initSupabaseClient();if(!client)return;const {error}=await client.auth.signInWithOAuth({provider:'google',options:{redirectTo:APP_URL}});if(error)accountStatus('Google 登入失敗：'+error.message,true)}
async function resizeAvatar(file){const bitmap=await createImageBitmap(file),size=256,canvas=document.createElement('canvas');canvas.width=size;canvas.height=size;const ctx=canvas.getContext('2d'),scale=Math.max(size/bitmap.width,size/bitmap.height),w=bitmap.width*scale,h=bitmap.height*scale;ctx.drawImage(bitmap,(size-w)/2,(size-h)/2,w,h);bitmap.close?.();return await new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('圖片轉換失敗')),'image/webp',.86))}
async function uploadCustomAvatar(file){if(!file)return;if(!currentUser){setSaveStatus('請先登入帳號，再上傳自訂頭像。');return}if(!/^image\/(png|jpeg|webp)$/.test(file.type)||file.size>5*1024*1024){setSaveStatus('請選擇 5MB 以下的 PNG、JPG 或 WebP 圖片。');return}if(!cloudLockOwned&&!await claimCloudDevice(false)){setSaveStatus('另一台裝置正在同步，這台目前不能更換頭像。');return}const oldKey=playerProfile.avatarKey,oldUrl=playerProfile.avatarUrl;try{setSaveStatus('正在處理頭像…');const blob=await resizeAvatar(file),client=initSupabaseClient(),path=`${currentUser.id}/avatar-${Date.now()}.webp`,{error}=await client.storage.from('avatars').upload(path,blob,{contentType:'image/webp',upsert:false,cacheControl:'31536000'});if(error)throw error;const {data}=client.storage.from('avatars').getPublicUrl(path);playerProfile.avatarKey='custom';playerProfile.avatarUrl=data.publicUrl;saveProfile(true,false,false);if(!await pushCloudProfile(true))throw new Error('雲端資料未同步，頭像沒有套用');renderProfileAvatar();renderAvatarPicker();refreshAccountCorner();setSaveStatus('自訂頭像已更新並同步。')}catch(e){playerProfile.avatarKey=oldKey;playerProfile.avatarUrl=oldUrl;saveProfile(true,false,false);renderProfileAvatar();renderAvatarPicker();setSaveStatus('頭像上傳失敗：'+e.message)}}
async function signOutAccount(){if(!currentUser)return;if(!await showConfirm('登出這台裝置','登出後本機存檔仍會保留；再次登入可載入雲端進度。','登出'))return;await releaseCloudDevice();const client=initSupabaseClient();if(client)await client.auth.signOut({scope:'local'});currentUser=null;cloudSaveVersion=0;updateAccountStatus();refreshProfileAuthBlocks()}
async function signOutAllDevices(){if(!currentUser)return;if(!await showConfirm('登出所有裝置','所有裝置的登入工作階段都會失效；本機存檔不會刪除。','全部登出',true))return;await releaseCloudDevice();const {error}=await initSupabaseClient().auth.signOut({scope:'global'});if(error)return setSaveStatus('登出失敗：'+error.message);currentUser=null;cloudSaveVersion=0;updateAccountStatus();backToHome()}
async function forcePullCloudProfile(){if(await showConfirm('使用雲端資料','確定要使用雲端資料覆蓋這台本機資料？','使用雲端'))await pullCloudProfile(true,'force')}
async function takeoverDevice(){if(await showConfirm('接管此裝置','這台會成為唯一可寫入雲端的同步裝置；原本裝置將轉為唯讀。','接管此裝置'))await claimCloudDevice(true)}
async function forcePushCloudProfile(){if(await showConfirm('本機覆蓋雲端','確定要用這台本機資料覆蓋雲端？其他裝置之後會載入這份資料。','覆蓋雲端',true)){if(await claimCloudDevice(true,false))await pushCloudProfile(true)}}
function refreshProfileAuthBlocks(){const logged=!!currentUser;$('saveTools')?.classList.toggle('hidden',logged);['profileLogoutBtn','profilePullCloudBtn','profileTakeoverDeviceBtn','profilePushCloudBtn'].forEach(id=>$(id)?.classList.toggle('hidden',!logged));$('accountSecurityPanel')?.classList.toggle('hidden',!logged);if($('accountSecurityEmail'))$('accountSecurityEmail').textContent=logged?`目前帳號：${currentUser.email||accountDisplayName()}｜${getDeviceName()}`:'登入後可管理帳號。'}
