const COLS=9, ROWS=5, CELL_W=100/COLS, CELL_H=100/ROWS;
const LEVELS={
  1:{level:1,name:'第一關：草坪試煉',shortName:'草坪試煉',codename:'lawnTrial',theme:'day',plantStart:150,zombieStart:450,plantAI:165,zombieAI:130,incomeMin:7800,incomeMax:11800,plantAIMin:2700,plantAIMax:6100,zombieAIMin:3800,zombieAIMax:7600,plantIncome:22,zombieAIIncome:22,zombieIncome:20,plantAIIncome:20,zombieWeights:['normal','normal','cone'],defense:'basic',winAfter:15000,difficulty:'入門 1｜基礎教學',cardText:'黃巾屍潮剛越過草坪外圍，守軍只剩最基礎的弓兵、盾將與軍糧官；先穩住五路防線，確認推車還能救急。',plantHint:'草坪外圍遭到第一波屍潮試探。用軍糧官撐補給，盾將擋線，蜀軍弓兵慢慢清掉一般與鐵甲僵屍。',zombieHint:'僵屍方先派一般僵屍偵查，再用鐵甲僵屍壓住薄弱路線；不要急著同一路硬撞，找守軍少的路突破推車。'},
  2:{level:2,name:'第二關：軍糧小徑',shortName:'軍糧小徑',codename:'supplyPath',theme:'day',cardArt:'assets/backgrounds/level-02-custom-card.webp',plantStart:170,zombieStart:560,plantAI:210,zombieAI:160,incomeMin:7200,incomeMax:10800,plantAIMin:2500,plantAIMax:5700,zombieAIMin:3600,zombieAIMax:7200,plantIncome:25,zombieAIIncome:25,zombieIncome:22,plantAIIncome:22,zombieWeights:['normal','normal','cone','bucket','peaZombie'],defense:'basicPlus',winAfter:18000,difficulty:'入門 2｜基礎進階',cardText:'軍糧車隊在小徑上被屍潮盯上，關羽火焰將趕來護糧；僵屍也開始用巨人與投石拆掉固定防線。',plantHint:'護住軍糧小徑是關鍵。關羽火焰將可斬斷單一路壓力，但軍糧官仍要提早布置才撐得起火力。',zombieHint:'獸之巨人負責吃傷害，擲石僵屍從後排拆盾；優先攻擊守方空缺或只有軍糧官的路線。'},
  3:{level:3,name:'第三關：白日突圍',shortName:'白日突圍',codename:'dayBreakout',theme:'day',cardArt:'assets/backgrounds/level-03-custom-card.webp',plantStart:195,zombieStart:660,plantAI:270,zombieAI:200,incomeMin:6600,incomeMax:9800,plantAIMin:2200,plantAIMax:5000,zombieAIMin:3300,zombieAIMax:6600,plantIncome:28,zombieAIIncome:30,zombieIncome:24,plantAIIncome:26,zombieWeights:['normal','cone','bucket','peaZombie','poleVault'],defense:'dayBreakout',winAfter:21000,difficulty:'普通 1｜速度壓力',cardText:'白日城門被多路騷擾，跳躍僵屍開始越過前排；寒冰趙雲奉命截擊，用緩速守住被突破的缺口。',plantHint:'跳躍僵屍會避開第一道防線，寒冰趙雲適合放在容易漏怪的中後段，緩住突入者。',zombieHint:'跳躍僵屍適合走有單一盾將或前排過密的路線；搭配鐵甲或擲石分散守軍注意。',openingZombies:['normal']},
  4:{level:4,name:'第四關：前線演武',shortName:'前線演武',codename:'frontDrill',theme:'day',cardArt:'assets/backgrounds/level-04-custom-card.webp',plantStart:220,zombieStart:760,plantAI:330,zombieAI:240,incomeMin:6000,incomeMax:9000,plantAIMin:1900,plantAIMax:4500,zombieAIMin:3000,zombieAIMax:6100,plantIncome:31,zombieAIIncome:34,zombieIncome:25,plantAIIncome:30,zombieWeights:['normal','cone','bucket','peaZombie','poleVault','football'],defense:'frontDrill',winAfter:24000,difficulty:'普通 2｜中階角色',cardText:'前線演武變成真正戰場，馬超與龐統投入中軍；屍潮派出僵屍王將軍測試哪一路最容易被斬首突破。',plantHint:'馬超能處理三格內的群聚敵人，龐統可在三列危急時放火救場；不要太早浪費一次性火攻。',zombieHint:'僵屍王將軍適合在守方後排薄弱時高速壓線；先用便宜僵屍騙出火攻，再集中突破。',openingZombies:['cone']},
  5:{level:5,name:'第五關：鐵甲夜襲',shortName:'鐵甲夜襲',codename:'bucketRush',theme:'night',cardArt:'assets/backgrounds/level-05-custom-card.webp',nightMode:true,plantStart:245,zombieStart:880,plantAI:420,zombieAI:290,incomeMin:5400,incomeMax:8300,plantAIMin:1600,plantAIMax:3900,zombieAIMin:2700,zombieAIMax:5400,plantIncome:34,zombieAIIncome:40,zombieIncome:27,plantAIIncome:34,zombieWeights:['normal','cone','cone','bucket','bucket','peaZombie','poleVault','football','jester'],defense:'bucketRush',winAfter:27000,difficulty:'進階 1｜夜襲',cardText:'夜色掩護下，鐵甲與小丑部隊分頭夜襲；黃忠登上高處，以三排箭雨支援看不清的側翼。',plantHint:'夜戰會讓多路壓力更頻繁。黃忠放在中路時可照顧上下排，適合補足防線空洞。',zombieHint:'小丑僵屍用狂笑干擾密集防線；若某一路守軍太多，先混亂它，若某一路人少就直接壓線。',openingZombies:['normal','cone']},
  6:{level:6,name:'第六關：夜半奔襲',shortName:'夜半奔襲',codename:'midnightRaid',theme:'night',cardArt:'assets/backgrounds/level-06-custom-card.webp',nightMode:true,plantStart:270,zombieStart:980,plantAI:495,zombieAI:340,incomeMin:5000,incomeMax:7800,plantAIMin:1450,plantAIMax:3500,zombieAIMin:2500,zombieAIMax:5000,plantIncome:36,zombieAIIncome:44,zombieIncome:29,plantAIIncome:38,zombieWeights:['normal','cone','bucket','bucket','peaZombie','poleVault','football','jester','bombJester'],defense:'midnightRaid',winAfter:30000,difficulty:'進階 2｜爆破登場',cardText:'夜半鼓聲逼近，炸彈小丑混入屍潮，準備用自爆打散守軍陣型；張飛扛起前線，硬把屍潮推回去。',plantHint:'張飛適合守最危險的缺口，靠高血量與反推拖住爆破單位；防線不要貼太密，避免被自爆連鎖。',zombieHint:'炸彈小丑要送進守軍密集處才有價值；若守軍分散，就改挑人少的一路用鐵甲和跳躍突破。',openingZombies:['cone','peaZombie']},
  7:{level:7,name:'第七關：火石攻城',shortName:'火石攻城',codename:'fireSiege',theme:'siege',cardArt:'assets/backgrounds/level-07-custom-card.webp',nightMode:true,plantStart:300,zombieStart:1080,plantAI:585,zombieAI:395,incomeMin:4500,incomeMax:7200,plantAIMin:1300,plantAIMax:3200,zombieAIMin:2300,zombieAIMax:4700,plantIncome:40,zombieAIIncome:50,zombieIncome:31,plantAIIncome:43,zombieWeights:['normal','cone','bucket','bucket','peaZombie','poleVault','football','jester','bombJester','corpseTitan'],defense:'fireSiege',winAfter:33000,difficulty:'將軍 1｜攻城巨屍',cardText:'城牆前燃起火石，屍旗巨魁扛著戰旗與攻城槌逼近；孔明布下八陣圖，準備在全線失守前逆轉戰局。',plantHint:'屍旗巨魁會震碎前排密集防線。孔明是全地圖救場牌，等多路同時危急時再出手。',zombieHint:'屍旗巨魁適合打守軍最多的關鍵路線，用九宮格震擊拆開城牆，再讓小兵從旁路補刀。',openingZombies:['cone','peaZombie']},
  8:{level:8,name:'第八關：烈焰破陣',shortName:'烈焰破陣',codename:'flameBreak',theme:'siege',nightMode:true,plantStart:325,zombieStart:1180,plantAI:680,zombieAI:445,incomeMin:4100,incomeMax:6700,plantAIMin:1200,plantAIMax:2950,zombieAIMin:2200,zombieAIMax:4500,plantIncome:42,zombieAIIncome:55,zombieIncome:33,plantAIIncome:48,zombieWeights:['normal','cone','bucket','peaZombie','poleVault','football','jester','bombJester','corpseTitan','fireCatapult','fireCatapult'],defense:'flameBreak',winAfter:36000,difficulty:'將軍 2｜投石車登場',cardText:'烈焰投石車推到陣前，火石專挑守軍最密集處落下；守方必須拉開陣型，避免一顆火石燒穿三路。',plantHint:'投石車會鎖定密集防線，守軍要錯位配置；用黃忠與馬超支援薄弱路，不要只堆同一格。',zombieHint:'投石車適合轟守軍最密集的一路，火石打開缺口後，再派快兵或巨魁改走沒人的路線。',openingZombies:['bucket','peaZombie']},
  9:{level:9,name:'第九關：群魔決戰',shortName:'群魔決戰',codename:'finalSiege',theme:'final',cardArt:'assets/backgrounds/level-09-custom-card.webp',nightMode:true,plantStart:355,zombieStart:1300,plantAI:790,zombieAI:510,incomeMin:3700,incomeMax:6200,plantAIMin:1120,plantAIMax:2750,zombieAIMin:2100,zombieAIMax:4250,plantIncome:45,zombieAIIncome:60,zombieIncome:35,plantAIIncome:55,zombieWeights:['normal','cone','bucket','peaZombie','poleVault','football','jester','bombJester','corpseTitan','fireCatapult','fireCatapult','qinEmperor'],defense:'finalSiege',winAfter:40000,difficulty:'決戰 1｜全角色解鎖',cardText:'群魔逼近主城，劉備親自召兵穩住人心；雙方所有將領都已到場，戰局會在多路牽制與破口判斷中決定。',plantHint:'劉備能定時召出三路刀兵，適合補上人手不足的線；孔明與龐統留給全線危急或密集屍潮。',zombieHint:'全僵屍解鎖後不要只打一線。先觀察哪一路守軍少、推車已用掉，再用攻城兵器與高速將軍連續突破。',openingZombies:['bucket','peaZombie','poleVault']},
  10:{level:10,name:'第十關：屍潮終局',shortName:'屍潮終局',codename:'deadTideFinal',theme:'final',cardArt:'assets/backgrounds/level-10-custom-card.webp',nightMode:true,plantStart:390,zombieStart:1450,plantAI:915,zombieAI:600,incomeMin:3300,incomeMax:5600,plantAIMin:950,plantAIMax:2400,zombieAIMin:1900,zombieAIMax:3900,plantIncome:48,zombieAIIncome:68,zombieIncome:38,plantAIIncome:62,zombieWeights:['normal','cone','bucket','peaZombie','poleVault','football','jester','bombJester','corpseTitan','fireCatapult','fireCatapult','corpseTitan','qinEmperor'],defense:'deadTideFinal',winAfter:45000,difficulty:'決戰 2｜第一階段最終關',cardText:'屍潮終局，所有火石、戰旗與爆破部隊同時壓上。這不是單一路的硬仗，而是考驗誰能先看出五路防線的破口。',plantHint:'最後一戰會不斷出現多路破口。用劉備補線、張飛守門、孔明與龐統輪流救場，避免第五路或邊線被偷穿。',zombieHint:'終局資源最高，但節奏要分段。初期慢慢探路，後期用投石車、屍旗與炸彈小丑輪流找空線攻破。',openingZombies:['bucket','peaZombie','poleVault','cone']}
};
const LEVEL_PACING={
  1:{difficultyRank:1,firstZombieDelay:7000,openingSpacing:6500,minSpawnSpacing:5000,enemyCount:14,attackTimeLimit:120000,bossType:'cone',bossHpMultiplier:1.7},
  2:{difficultyRank:2,firstZombieDelay:7000,openingSpacing:6500,minSpawnSpacing:4900,enemyCount:16,attackTimeLimit:130000,bossType:'bucket',bossHpMultiplier:1.8},
  3:{difficultyRank:3,firstZombieDelay:7000,openingSpacing:6400,minSpawnSpacing:4800,enemyCount:18,attackTimeLimit:140000,bossType:'poleVault',bossHpMultiplier:2},
  4:{difficultyRank:4,firstZombieDelay:7000,openingSpacing:6300,minSpawnSpacing:4700,enemyCount:20,attackTimeLimit:150000,bossType:'football',bossHpMultiplier:2},
  5:{difficultyRank:5,firstZombieDelay:9000,openingSpacing:6800,minSpawnSpacing:4600,enemyCount:22,attackTimeLimit:160000,bossType:'jester',bossHpMultiplier:2.1},
  6:{difficultyRank:6,firstZombieDelay:9000,openingSpacing:6800,minSpawnSpacing:4500,enemyCount:25,attackTimeLimit:175000,bossType:'bombJester',bossHpMultiplier:2.2},
  7:{difficultyRank:7,firstZombieDelay:9000,openingSpacing:6900,minSpawnSpacing:4400,enemyCount:28,attackTimeLimit:190000,bossType:'corpseTitan',bossHpMultiplier:2.2},
  8:{difficultyRank:8,firstZombieDelay:9000,openingSpacing:7000,minSpawnSpacing:4300,enemyCount:31,attackTimeLimit:205000,bossType:'fireCatapult',bossHpMultiplier:2.3},
  9:{difficultyRank:9,firstZombieDelay:10000,openingSpacing:7200,minSpawnSpacing:4200,enemyCount:34,attackTimeLimit:220000,bossType:'corpseTitan',bossHpMultiplier:2.6},
  10:{difficultyRank:10,firstZombieDelay:10000,openingSpacing:7400,minSpawnSpacing:4000,enemyCount:36,attackTimeLimit:240000,bossType:'fireCatapult',bossHpMultiplier:3}
};
Object.values(LEVELS).forEach(level=>Object.assign(level,LEVEL_PACING[level.level]));
const PLANT_TYPES={peashooter:{name:'蜀軍弓兵',cost:100,emoji:'🏹',asset:'assets/characters/shu-archer.webp',hp:120,rate:1500,damage:22,range:9,cooldown:5200,desc:'基礎遠程射箭'},sunflower:{name:'軍糧官',cost:50,emoji:'🌾',asset:'assets/characters/quartermaster-strategist.webp',hp:90,rate:8500,produce:25,cooldown:4200,desc:'週期補充軍糧'},wallnut:{name:'盾將',cost:50,emoji:'🛡️',asset:'assets/characters/shield-general.webp',hp:420,cooldown:7000,desc:'高血量阻擋'},firepea:{name:'關羽火焰將',cost:175,emoji:'🔥',asset:'assets/characters/guanyu-fire-general.webp',hp:120,rate:1250,damage:42,range:9,fire:true,cooldown:9500,desc:'青龍火斬高傷害'},potato:{name:'伏兵',cost:25,emoji:'🥷',asset:'assets/characters/ambush-scout.webp',hp:60,armedAfter:4500,damage:260,cooldown:8500,desc:'延遲啟動突襲陷阱'},zhangfei:{name:'鬥神張飛',cost:225,emoji:'⚔️',asset:'assets/characters/future-generals/god-zhangfei.webp',hp:560,rate:2300,damage:62,range:1.15,knockback:1,cooldown:13000,desc:'高防高攻，近戰反推一格'},zhaoyun:{name:'寒冰趙雲',cost:175,emoji:'❄️',asset:'assets/characters/future-generals/ice-zhaoyun.webp',hp:210,rate:1350,damage:18,meleeDamage:48,range:9,slow:true,cooldown:10000,desc:'遠程緩速，近距離高傷'},machao:{name:'穿刺馬超',cost:200,emoji:'🗡️',asset:'assets/characters/future-generals/pierce-machao.webp',hp:250,rate:1800,damage:78,range:3.1,pierce:true,cooldown:11000,desc:'三格穿刺，可同時打多人'},huangzhong:{name:'百箭黃忠',cost:200,emoji:'🏹',asset:'assets/characters/future-generals/hundred-arrows-huangzhong.webp',hp:150,rate:1900,damage:22,range:9,tripleShot:true,cooldown:11500,desc:'一次射三排'},kongming:{name:'軍神孔明',cost:250,emoji:'🌪️',asset:'assets/characters/future-generals/war-god-kongming.webp',hp:1,oneUse:'global',damage:150,cooldown:15000,desc:'全地圖一次性高輸出'},pangtong:{name:'火神龐統',cost:175,emoji:'🔥',asset:'assets/characters/future-generals/fire-god-pangtong.webp',hp:1,oneUse:'row',damage:230,cooldown:12000,desc:'三列火攻一次性高輸出'},liubei:{name:'仁德劉備',cost:300,emoji:'👑',asset:'assets/characters/future-generals/liubei/liubei-main.webp',guideAsset:'assets/characters/future-generals/liubei/liubei-guide.webp',actionAsset:'assets/characters/future-generals/liubei/liubei-rally.webp',hp:330,rate:1800,damage:0,range:9,summon:true,summonRate:6500,cooldown:16000,desc:'普通攻擊召喚一名鄉勇；超級技能召喚上、中、下三路白毦禁衛'},swordSoldier:{name:'蜀軍鄉勇',cost:0,emoji:'⚔️',asset:'assets/characters/ambush-scout.webp',hp:95,damage:18,rate:900,range:.55,speed:.018,hidden:true,desc:'劉備普通攻擊召喚的綠衣輕裝兵'},whiteFeatherGuard:{name:'白毦禁衛',cost:0,emoji:'🛡️',asset:'assets/characters/shield-general.webp',hp:230,damage:42,rate:750,range:.8,speed:.014,hidden:true,elite:true,desc:'劉備超級技能召喚的紅金重甲精銳盾兵'}};
const ZOMBIE_TYPES={normal:{name:'一般僵屍',cost:50,emoji:'🧟',asset:'assets/characters/zombie-army/normal-zombie.webp',hp:110,speed:.018,damage:18,range:.35,cooldown:3600,desc:'便宜基本兵'},cone:{name:'鐵甲僵屍',cost:75,emoji:'🛡️',asset:'assets/characters/zombie-army/armored-zombie.webp',hp:190,speed:.016,damage:18,range:.35,cooldown:5200,desc:'中階防禦'},bucket:{name:'獸之巨人',cost:100,emoji:'👹',asset:'assets/characters/zombie-army/beast-giant.webp',hp:290,speed:.013,damage:20,range:.35,cooldown:6500,desc:'高血量重壓'},football:{name:'僵屍王將軍',cost:200,emoji:'💀',asset:'assets/characters/zombie-army/zombie-warlord.webp',hp:380,speed:.031,damage:34,range:.35,cooldown:11000,desc:'強力菁英'},jester:{name:'小丑僵屍',cost:225,emoji:'🃏',asset:'assets/characters/zombie-army/jester-general-zombie.webp',hp:360,speed:.015,damage:26,range:.45,laugh:true,laughRate:5200,laughDamage:34,laughStun:2600,cooldown:12500,desc:'將軍級混亂術師，狂笑震懾同一路守方'},bombJester:{name:'炸彈小丑',cost:250,emoji:'💣',asset:'assets/characters/zombie-army/bomb-jester-general-zombie.webp',hp:340,speed:.014,damage:24,range:.45,bombDeath:true,bombDamage:220,bombRadius:1,cooldown:14500,desc:'將軍級爆破指揮官，倒下後九宮格自爆'},corpseTitan:{name:'屍旗巨魁',cost:325,emoji:'🏴‍☠️',asset:'assets/characters/zombie-army/corpse-banner-titan-zombie.webp',hp:760,speed:.0095,damage:38,range:.58,siegeSmash:true,smashRate:2100,smashDamage:78,smashStun:1400,cooldown:19000,desc:'將軍級攻城巨屍，巨槌震碎九宮格防線'},fireCatapult:{name:'投石車僵屍',cost:350,emoji:'☄️',asset:'assets/characters/zombie-army/fire-catapult-zombie.webp',hp:620,speed:.0075,damage:24,range:.45,catapult:true,catapultRange:8,catapultRate:3600,catapultDamage:92,catapultSplash:.58,cooldown:22000,desc:'將軍級攻城投石車，遠距離火石轟炸九宮格'},peaZombie:{name:'擲石僵屍',cost:100,emoji:'🪨',asset:'assets/characters/zombie-army/rock-thrower-zombie.webp',hp:95,speed:.013,damage:16,range:4.5,shoot:true,cooldown:7600,desc:'遠程投石'},poleVault:{name:'跳躍僵屍',cost:125,emoji:'🧟‍♂️',asset:'assets/characters/zombie-army/jumping-zombie.webp',spentEmoji:'🧟',spentAsset:'assets/characters/zombie-army/normal-zombie.webp',hp:140,speed:.034,spentSpeed:.018,damage:18,range:.35,canJump:true,cooldown:8200,desc:'第二關新增，先快跑並跳過一名守方角色'},qinEmperor:{name:'始皇屍帝・嬴政',cost:350,emoji:'👑',asset:'assets/characters/zombie-army/undead-qin-emperor.webp',hp:420,speed:.0105,damage:0,range:.55,summon:true,summonRate:6500,cooldown:20000,desc:'兵馬俑召令召出秦俑屍兵；大秦軍陣改召三路玄甲禁軍'},terracottaSoldier:{name:'秦俑屍兵',cost:0,emoji:'⚔️',asset:'assets/characters/zombie-army/qin-terracotta-soldier.webp',hp:90,speed:.019,damage:16,rate:850,range:.4,hidden:true,desc:'始皇屍帝普通攻擊召喚的秦俑屍兵'},blackArmorGuard:{name:'玄甲禁軍',cost:0,emoji:'🛡️',asset:'assets/characters/zombie-army/qin-black-guard.webp',hp:220,speed:.015,damage:40,rate:700,range:.7,hidden:true,elite:true,desc:'始皇屍帝機率技能召喚的黑金重甲禁軍'}};
