const SHOP_ITEMS=[
 {key:'archerQuiver',type:'equipment',rarity:'common',side:'plants',target:'peashooter',name:'蜀軍箭袋',price:120,desc:'蜀軍弓兵遠戰攻擊 +8%。',effect:{damagePct:.08}},
 {key:'grainBanner',type:'equipment',rarity:'common',side:'plants',target:'sunflower',name:'軍糧旗令',price:120,desc:'軍糧官產糧 +8%。',effect:{producePct:.08}},
 {key:'wallShield',type:'equipment',rarity:'common',side:'plants',target:'wallnut',name:'玄鐵盾面',price:130,desc:'盾將 HP +10%。',effect:{hpPct:.10}},
 {key:'ambushBoots',type:'equipment',rarity:'rare',side:'plants',target:'potato',name:'伏兵疾靴',price:150,desc:'伏兵爆發傷害 +8%、冷卻 -3%。',effect:{damagePct:.08,cooldownPct:-.03}},
 {key:'greenDragonArmor',type:'equipment',rarity:'epic',side:'plants',target:'firepea',name:'青龍戰袍',price:180,desc:'關羽 HP +10%、火焰傷害 +6%。',effect:{hpPct:.10,damagePct:.06}},
 {key:'iceSpearCharm',type:'equipment',rarity:'epic',side:'plants',target:'zhaoyun',name:'冰槍符石',price:180,desc:'趙雲近戰/遠戰攻擊 +7%，冷卻 -4%。',effect:{damagePct:.07,cooldownPct:-.04}},
 {key:'phoenixFan',type:'equipment',rarity:'legend',side:'plants',target:'pangtong',name:'鳳羽軍扇',price:260,desc:'龐統鳳火傷害 +10%。',effect:{damagePct:.10}},
 {key:'lanceSaddle',type:'equipment',rarity:'epic',side:'plants',target:'machao',name:'突騎銀鞍',price:220,desc:'馬超穿刺傷害 +9%、冷卻 -4%。',effect:{damagePct:.09,cooldownPct:-.04}},
 {key:'goldenBow',type:'equipment',rarity:'legend',side:'plants',target:'huangzhong',name:'百步金弓',price:260,desc:'黃忠箭雨傷害 +10%。',effect:{damagePct:.10}},
 {key:'roarDrum',type:'equipment',rarity:'epic',side:'plants',target:'zhangfei',name:'虎吼戰鼓',price:220,desc:'張飛 HP +8%、擊退攻擊 +7%。',effect:{hpPct:.08,damagePct:.07}},
 {key:'starRobe',type:'equipment',rarity:'legend',side:'plants',target:'kongming',name:'七星羽衣',price:320,desc:'孔明八陣雷擊傷害 +12%。',effect:{damagePct:.12}},
 {key:'virtueSeal',type:'equipment',rarity:'legend',side:'plants',target:'liubei',name:'仁德玉印',price:320,desc:'劉備 HP +8%，召喚刀兵更強。',effect:{hpPct:.08,summonPct:.08}},
 {key:'ironHelmet',type:'equipment',rarity:'common',side:'zombies',target:'cone',name:'鐵角盔',price:100,desc:'鐵甲僵屍 HP +8%。',effect:{hpPct:.08}},
 {key:'boneArmor',type:'equipment',rarity:'rare',side:'zombies',target:'bucket',name:'獸骨厚甲',price:140,desc:'獸之巨人 HP +12%。',effect:{hpPct:.12}},
 {key:'vaultPole',type:'equipment',rarity:'rare',side:'zombies',target:'poleVault',name:'飛躍竹竿',price:160,desc:'跳躍僵屍攻擊 +8%、冷卻 -3%。',effect:{damagePct:.08,cooldownPct:-.03}},
 {key:'catapultOil',type:'equipment',rarity:'legend',side:'zombies',target:'fireCatapult',name:'烈焰火油',price:260,desc:'投石車火石傷害 +9%。',effect:{damagePct:.09}},
 {key:'guanyuSkill',type:'skill',rarity:'epic',side:'plants',target:'firepea',name:'青龍火斬 Lv.2',price:240,desc:'關羽技能/遠戰傷害 +12%。',effect:{damagePct:.12}},
 {key:'zhaoyunSkill',type:'skill',rarity:'epic',side:'plants',target:'zhaoyun',name:'冰龍槍法',price:240,desc:'趙雲攻擊 +10%、冷卻 -5%。',effect:{damagePct:.10,cooldownPct:-.05}},
 {key:'pangtongSkill',type:'skill',rarity:'legend',side:'plants',target:'pangtong',name:'鳳火連營',price:320,desc:'龐統鳳火傷害 +14%。',effect:{damagePct:.14}},
 {key:'huangzhongSkill',type:'skill',rarity:'legend',side:'plants',target:'huangzhong',name:'穿雲箭訣',price:320,desc:'黃忠三路箭雨傷害 +14%。',effect:{damagePct:.14}},
 {key:'liubeiVirtue',type:'skill',rarity:'legend',side:'plants',target:'liubei',name:'仁德治世',price:300,desc:'劉備召喚刀兵 HP/攻擊 +10%。',effect:{summonPct:.10}},
 {key:'jesterChaos',type:'skill',rarity:'epic',side:'zombies',target:'jester',name:'亂陣狂笑強化',price:260,desc:'小丑狂笑傷害 +12%、冷卻 -5%。',effect:{damagePct:.12,cooldownPct:-.05}},
 {key:'titanSmashSkill',type:'skill',rarity:'legend',side:'zombies',target:'corpseTitan',name:'破城屍槌奧義',price:320,desc:'屍旗巨魁重槌傷害 +14%。',effect:{damagePct:.14}},
 {key:'redFrame',type:'skin',rarity:'rare',side:'plants',target:'all',name:'赤焰卡框',price:90,desc:'守方卡片赤焰外觀，不增加戰力。',skinClass:'skin-red'},
 {key:'blueFrame',type:'skin',rarity:'rare',side:'zombies',target:'all',name:'幽藍屍潮卡框',price:90,desc:'僵屍方幽藍卡框，不增加戰力。',skinClass:'skin-blue'},
 {key:'royalGoldFrame',type:'skin',rarity:'legend',side:'plants',target:'all',name:'王者金框',price:180,desc:'三國守方金色收藏外觀，不增加戰力。',skinClass:'skin-red'},
 {key:'darkArmyFrame',type:'skin',rarity:'legend',side:'zombies',target:'all',name:'屍潮暗金框',price:180,desc:'僵屍方暗金收藏外觀，不增加戰力。',skinClass:'skin-blue'}
];
let shopType='equipment';
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function baseUnit(roster,key){return (roster==='plants'?PLANT_TYPES:ZOMBIE_TYPES)[key]}
function charLevel(roster,key){return playerProfile.characterLevels?.[roster]?.[key]?.level||1}
function ownedShopItem(key){const it=SHOP_ITEMS.find(x=>x.key===key);return !!(it&&playerProfile.inventory?.[it.type==='skill'?'skills':it.type==='skin'?'skins':'equipment']?.[key])}
function effectItems(roster,key){return SHOP_ITEMS.filter(it=>it.side===roster&&(it.target===key||it.target==='all')&&ownedShopItem(it.key)&&(it.type==='skill'||it.type==='skin'||playerProfile.inventory?.equipped?.[roster]?.[key]===it.key))}
function sumEffects(roster,key){const bundle={hpPct:0,damagePct:0,ratePct:0,cooldownPct:0,producePct:0,summonPct:0};effectItems(roster,key).forEach(it=>Object.entries(it.effect||{}).forEach(([k,v])=>bundle[k]=(bundle[k]||0)+v));return bundle}
function scaleNum(v,pct){return v==null?v:Math.max(1,Math.round(v*(1+pct)))}
function effectiveUnit(roster,key,next=0){const d=baseUnit(roster,key);if(!d)return d;const lv=charLevel(roster,key)+next,levelPct=Math.max(0,lv-1);const eff=sumEffects(roster,key),out={...d};const hpPct=levelPct*.07+(eff.hpPct||0),dmgPct=levelPct*.055+(eff.damagePct||0),ratePct=Math.max(-.22,-levelPct*.012+(eff.ratePct||0)),coolPct=Math.max(-.25,-levelPct*.012+(eff.cooldownPct||0));['hp'].forEach(k=>out[k]=scaleNum(out[k],hpPct));['damage','meleeDamage','catapultDamage','smashDamage','bombDamage','laughDamage'].forEach(k=>out[k]=scaleNum(out[k],dmgPct));if(out.produce)out.produce=scaleNum(out.produce,levelPct*.04+(eff.producePct||0));if(out.rate)out.rate=Math.max(350,Math.round(out.rate*(1+ratePct)));if(out.catapultRate)out.catapultRate=Math.max(1200,Math.round(out.catapultRate*(1+ratePct)));if(out.smashRate)out.smashRate=Math.max(900,Math.round(out.smashRate*(1+ratePct)));if(out.laughRate)out.laughRate=Math.max(1600,Math.round(out.laughRate*(1+ratePct)));if(out.cooldown)out.cooldown=Math.max(1500,Math.round(out.cooldown*(1+coolPct)));if(key==='swordSoldier'&&ownedShopItem('liubeiVirtue')){out.hp=scaleNum(out.hp,.10);out.damage=scaleNum(out.damage,.10)}return out}
function activeUnit(roster,key){return state&&state.faction===roster?effectiveUnit(roster,key):baseUnit(roster,key)}
async function upgradeCharacter(roster,key){const rec=playerProfile.characterLevels?.[roster]?.[key];if(!rec)return;const need=characterXpNeed(rec.level);if(rec.xp<need){setSaveStatus(`XP 不足：還需要 ${need-rec.xp}。`);sfx('click');return}if(currentUser){if(!cloudLockOwned&&!await claimCloudDevice(false))return;const {data,error}=await initSupabaseClient().rpc('sgz_upgrade_character',{p_device_id:getDeviceId(),p_roster:roster,p_character_key:key});if(error)return setSaveStatus('升級失敗：'+cloudErrorMessage(error));applyCloudResult(data)}else{rec.xp-=need;rec.level++;saveProfile()}renderCharacterLevels(roster);setSaveStatus(`${baseUnit(roster,key).name} 已升級，戰力已套用。`);sfx('coin')}
function showShop(type=shopType){shopType=type;playSceneMusic('stageSelect');['start','accountScreen','levelScreen','game','characters','profile'].forEach(id=>$(id)?.classList.remove('active'));$('shop').classList.add('active');renderShop()}
function shopCategoryMeta(type=shopType){return {equipment:['裝備補給','替指定角色裝備戰具，直接提升戰鬥數值。','⚔️'],skill:['技能秘卷','購買後永久強化指定技能，登入帳號會同步保存。','📜'],skin:['外觀收藏','收藏並套用陣營外觀，不增加戰力但會保留在帳號資料。','🎨']}[type]||['商城','選擇商品開始強化陣容。','🛒']}
function shopRarityLabel(r){return {common:'普通',rare:'稀有',epic:'史詩',legend:'傳說'}[r]||'普通'}
function shopItemIcon(it){if(it.type==='skill')return '📜';if(it.type==='skin')return '🎨';return it.side==='plants'?'⚔️':'🧟'}
function updateShopSyncBadge(){const b=$('shopSyncBadge');if(!b)return;b.textContent=currentUser?(cloudLockOwned?'☁️ 已登入・自動同步':'🔒 已登入・這台唯讀'):'💾 未登入・本機存檔';b.classList.toggle('local',!currentUser||!cloudLockOwned)}
function renderShop(){if(!$('shopGrid'))return;document.querySelectorAll('[data-shop-type]').forEach(b=>{const on=b.dataset.shopType===shopType;b.classList.toggle('active',on);b.classList.toggle('primary',on);b.classList.toggle('secondary',!on)});const [title,desc]=shopCategoryMeta(shopType);if($('shopSectionTitle'))$('shopSectionTitle').textContent=title;if($('shopSectionDesc'))$('shopSectionDesc').textContent=desc;updateShopSyncBadge();$('shopWallet').innerHTML=[['玩家',playerProfile.name||'訪客將軍'],['金幣',`🪙 ${playerProfile.gold||0}`],['等級',`Lv.${playerProfile.level||1}`],['同步',currentUser?'雲端帳號':'本機']].map(([k,v])=>`<div class="profile-stat"><b>${escapeHtml(k)}</b><span>${escapeHtml(v)}</span></div>`).join('');$('shopGrid').innerHTML=SHOP_ITEMS.filter(it=>it.type===shopType).map(it=>{const owned=ownedShopItem(it.key),equipped=playerProfile.inventory?.equipped?.[it.side]?.[it.target]===it.key,skinActive=it.type==='skin'&&playerProfile.inventory?.activeSkins?.[it.side]===it.skinClass,side=it.side==='plants'?'三國守方':'僵屍方',target=it.target==='all'?'全體外觀':baseUnit(it.side,it.target)?.name,action=owned?(it.type==='equipment'?'已購買，可裝備':it.type==='skin'?'已購買，可套用':'永久生效'):'尚未購買';return `<article class="shop-item rarity-${it.rarity||'common'}"><div class="shop-item-top"><div class="shop-icon">${shopItemIcon(it)}</div><div><h3>${it.name}</h3><small>${side}｜${target}</small><span class="rarity-pill">${shopRarityLabel(it.rarity)}</span></div></div><p>${it.desc}</p><div class="shop-price">🪙 ${it.price}</div> ${owned?'<span class="owned-pill">已擁有</span>':''}${equipped||skinActive?'<span class="equipped-pill">使用中</span>':''}<small>${action}</small><button class="${owned?'secondary':'primary'}" onclick="buyShopItem('${it.key}')">${owned?'已購買':'購買'}</button>${owned&&it.type==='equipment'?`<button class="secondary equip-btn" onclick="equipShopItem('${it.key}')">裝備</button>`:''}${owned&&it.type==='skin'?`<button class="secondary equip-btn" onclick="activateSkin('${it.key}')">套用外觀</button>`:''}</article>`}).join('')}
async function buyShopItem(key){const it=SHOP_ITEMS.find(x=>x.key===key);if(!it||ownedShopItem(key)){renderShop();return}if((playerProfile.gold||0)<it.price){setSaveStatus(`金幣不足：還需要 ${it.price-(playerProfile.gold||0)}。`);sfx('click');return}if(currentUser){if(!cloudLockOwned&&!await claimCloudDevice(false))return;const {data,error}=await initSupabaseClient().rpc('sgz_buy_item',{p_device_id:getDeviceId(),p_item_key:key});if(error)return setSaveStatus('購買失敗：'+cloudErrorMessage(error));applyCloudResult(data)}else{playerProfile.gold-=it.price;const bucket=it.type==='skill'?'skills':it.type==='skin'?'skins':'equipment';playerProfile.inventory[bucket][key]=1;if(it.type==='equipment')playerProfile.inventory.equipped[it.side][it.target]=key;saveProfile()}renderShop();setSaveStatus(`已購買 ${it.name}。`);sfx('coin')}
async function equipShopItem(key){const it=SHOP_ITEMS.find(x=>x.key===key);if(!it||!ownedShopItem(key))return;if(currentUser){if(!cloudLockOwned&&!await claimCloudDevice(false))return;const {data,error}=await initSupabaseClient().rpc('sgz_equip_item',{p_device_id:getDeviceId(),p_item_key:key});if(error)return setSaveStatus('裝備失敗：'+cloudErrorMessage(error));applyCloudResult(data)}else{playerProfile.inventory.equipped[it.side][it.target]=key;saveProfile()}renderShop();renderCharacterLevels(profileRoster);setSaveStatus(`已裝備 ${it.name}。`)}
function applyActiveSkins(){document.body.classList.remove('skin-red','skin-blue');Object.values(playerProfile.inventory?.activeSkins||{}).forEach(cls=>cls&&document.body.classList.add(cls))}
