const {test,expect}=require('@playwright/test');
async function open(page){await page.route('https://cdn.jsdelivr.net/**',r=>r.fulfill({body:''}));await page.goto('/');}
test('season two intro waits, can cancel, and season one read flags cannot suppress it',async({page})=>{
 await open(page);await page.evaluate(()=>{markStoryRead('plants',1,'opening');chooseFaction('plants',2);window.__starts=0;startCloudMatch=()=>{window.__starts++;return Promise.resolve()}});await page.locator('[data-jump-level="1"]').click();await expect(page.locator('#storyDialog')).toBeVisible();await expect(page.locator('#storyRoute')).toContainText('北境鐵壁');expect(await page.evaluate(()=>window.__starts)).toBe(0);
 await page.locator('#storyClose').click();expect(await page.evaluate(()=>hasReadStory('plants',1,'opening',2))).toBe(false);await page.locator('[data-jump-level="1"]').click();await page.locator('#storySkip').click();await expect(page.locator('#game')).toHaveClass(/active/);expect(await page.evaluate(()=>window.__starts)).toBe(1);
 await page.evaluate(()=>pauseAndSaveBattle());await page.reload();await expect(page.locator('#storyDialog')).not.toBeVisible();expect(await page.evaluate(()=>state.paused)).toBe(true);
});
test('both routes have twelve scenes, real portraits, isolated reads and guarded victory replay',async({page})=>{
 await open(page);expect(await page.evaluate(()=>typeof SEASON2_STORY)).toBe('object');
 const out=await page.evaluate(async()=>{currentSeason=2;const issues=[],portraits=new Set();let count=0;for(const side of ['plants','zombies'])for(let level=1;level<=2;level++)for(const scene of ['opening','victory','defeat']){if(!openCampaignStory(side,level,scene,{season:2,replay:true})){issues.push('missing');continue}count++;for(let i=0;i<activeCampaignStory.lines.length;i++){activeCampaignStory.index=i;renderCampaignStory();const img=document.getElementById('storyPortrait');if(activeCampaignStory.lines[i].speaker==='旁白'){if(!img.hidden)issues.push('narrator portrait')}else if(img.hidden)issues.push(activeCampaignStory.lines[i].speaker);else portraits.add(img.src)}closeCampaignStory(false)}await Promise.all([...portraits].map(async src=>{const im=new Image();im.src=src;await im.decode()}));return {count,issues,locked:replayCampaignStory('plants',2),victory:replayCampaignStory('plants',1,'victory')}});
 expect(out).toEqual({count:12,issues:[],locked:false,victory:false});
});
test('second stage victory stays on results, next stage is bounded, replay never changes rewards',async({page})=>{
 await open(page);await page.evaluate(()=>{completeCampaignLevel('plants',1,2);chooseFaction('plants',2)});await page.locator('[data-jump-level="2"]').click();await expect(page.locator('#storyTitle')).toContainText('石壘營門');await page.locator('#storySkip').click();await page.evaluate(async()=>{clearInterval(timer);await end(true,'勝利','fixture')});await expect(page.locator('#storyDialog')).not.toBeVisible();await expect(page.locator('#rewardPanel')).toBeVisible();await page.locator('#modalStory').click();await expect(page.locator('#storyDialog')).toBeVisible();await page.locator('#storySkip').click();
 expect(await page.evaluate(()=>hasReadStory('plants',2,'victory',1))).toBe(false);const gold=await page.evaluate(()=>playerProfile.gold);await page.evaluate(()=>{backToLevelSelect();replayCampaignStory('plants',2,'victory')});await page.locator('#storySkip').click();expect(await page.evaluate(()=>playerProfile.gold)).toBe(gold);await expect(page.locator('[data-jump-level="3"]')).toBeDisabled();
});
