const {test,expect}=require('@playwright/test');
async function setup(page,season=1,level=6){await page.route('https://cdn.jsdelivr.net/**',r=>r.fulfill({body:''}));await page.goto(process.env.GAME_URL||'/');await page.evaluate(({season,level})=>{currentSeason=season;for(let l=1;l<level;l++)completeCampaignLevel('plants',l,season);saveProfile();selectedLevel=level;start('plants');clearInterval(timer);state.openingQueue=[];state.time=80000;state.enemiesSpawned=state.waveDirector.plan[0].after-1;state.nextAI=state.time+9000;aiAct();updateHUD()},{season,level})}
test('all authored waves have distinct scouting, entry lines and real speaker art',async({page})=>{await setup(page);const result=await page.evaluate(()=>{const issues=[];for(const season of [1,2])for(const lv of Object.values(campaignLevels(season))){const d=createDefenseWaves(lv),copy=DEFENSE_WAVE_STORY[season][lv.level];if(copy.scout.length!==d.plan.length||copy.charge.length!==d.plan.length)issues.push('count');for(const text of [...copy.scout,...copy.charge])if(!text||text.length>48)issues.push('copy');}return issues});expect(result).toEqual([])});
test('every interlude renders its authored line and decodes its actual portrait',async({page})=>{
 await setup(page);const issues=await page.evaluate(async()=>{const issues=[];for(const season of [1,2])for(const lv of Object.values(campaignLevels(season))){state.season=season;state.level=lv.level;state.levelConfig=lv;for(const kind of ['scout','charge'])for(let i=0;i<DEFENSE_WAVE_STORY[season][lv.level][kind].length;i++){state.waveDirector=createDefenseWaves(lv);emitDefenseWaveStory(kind,i);updateHUD();const e=state.waveDirector.story.event,img=document.getElementById('waveStoryPortrait');if(!e||document.getElementById('waveStory').hidden||!document.getElementById('waveStoryText').textContent.includes(DEFENSE_WAVE_STORY[season][lv.level][kind][i]))issues.push(`${season}/${lv.level}/${kind}/${i}`);try{await img.decode()}catch{issues.push('portrait '+img.src)}}}return issues});expect(issues).toEqual([]);
});
test('scouting precedes the countdown; dismiss and reload preserve state, actual entry speaks once',async({page})=>{
 await setup(page);await expect(page.locator('#waveStory')).toBeVisible();await expect(page.locator('#waveBrief')).toContainText('第 1/3 波');await expect(page.locator('#waveStatus')).not.toContainText('5 秒');
 const before=await page.evaluate(()=>({food:state.resource,brain:state.aiResource,time:state.time,quota:state.enemiesSpawned}));await page.locator('#waveStorySkip').click();await expect(page.locator('#waveStory')).toBeHidden();
 expect(await page.evaluate(()=>({food:state.resource,brain:state.aiResource,time:state.time,quota:state.enemiesSpawned}))).toEqual(before);await expect(page.locator('#waveBrief')).toBeVisible();
 await page.reload();expect(await page.evaluate(()=>state.paused)).toBe(true);await expect(page.locator('#waveStory')).toBeHidden();
 await page.evaluate(()=>{clearInterval(timer);state.paused=false;state.time=89000;aiAct();aiAct();updateHUD()});await expect(page.locator('#waveStatus')).toContainText('5 秒');await expect(page.locator('#waveStory')).toBeHidden();
 const entry=await page.evaluate(()=>{state.time=state.waveDirector.active.nextAt;aiAct();updateHUD();const e=JSON.stringify(state.waveDirector.story);for(let i=0;i<20;i++)updateHUD();return{same:e===JSON.stringify(state.waveDirector.story),sent:state.waveDirector.active.sent,key:state.waveDirector.story.event.key}});expect(entry).toMatchObject({same:true,sent:1,key:'charge-1'});await expect(page.locator('#waveStory')).toBeVisible();
 await page.evaluate(()=>{state.paused=true;persistBattleState()});const saved=await page.evaluate(()=>state.waveDirector.story);await page.reload();expect(await page.evaluate(()=>state.waveDirector.story)).toEqual(saved);
 await page.evaluate(()=>{clearInterval(timer);state.paused=false;state.time=state.waveDirector.story.event.until+1;updateHUD()});await expect(page.locator('#waveStory')).toBeHidden();
});
test('story does not alter seeded spawns, budgets or pause and stays off in legacy/attack battles',async({page})=>{await setup(page);const out=await page.evaluate(()=>{const results=[];for(const enabled of [false,true]){let seed=99;Math.random=()=>((seed=Math.imul(seed,1664525)+1013904223>>>0)/4294967296);start('plants');clearInterval(timer);if(!enabled)delete state.waveDirector.story;for(let t=0;t<450000&&!state.bossSpawned;t+=50){state.time=t;income();processLevelEvents();aiAct()}results.push({enemies:state.zombies.map(z=>[z.type,z.r]),brain:state.aiResource,time:state.time})}state.paused=true;const saved=JSON.stringify(state.waveDirector);aiAct();const paused=saved===JSON.stringify(state.waveDirector);delete state.waveDirector.story;updateHUD();const legacy=document.getElementById('waveStory').hidden;currentSeason=2;selectedLevel=1;start('zombies');clearInterval(timer);updateHUD();return{equal:JSON.stringify(results[0])===JSON.stringify(results[1]),paused,legacy,attack:document.getElementById('waveStatus').hidden}});expect(out).toEqual({equal:true,paused:true,legacy:true,attack:true})});
test('short story, actual portraits and grid remain usable on phone and fullscreen',async({page},info)=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await setup(page,1,10);
 for(const viewport of [{width:390,height:844},{width:844,height:390},{width:1440,height:900}]){await page.setViewportSize(viewport);await page.locator('#waveStatus').scrollIntoViewIfNeeded();await page.waitForFunction(()=>{const i=document.getElementById('waveStoryPortrait');return i.complete&&i.naturalWidth>0});const box=await page.locator('#waveStatus').boundingBox();expect(box.x+box.width).toBeLessThanOrEqual(viewport.width+1);expect(await page.locator('#waveStoryText').evaluate(e=>e.scrollHeight<=e.clientHeight+1)).toBe(true);await page.screenshot({path:info.outputPath('story-'+viewport.width+'.png')})}
 await page.setViewportSize({width:844,height:390});await page.locator('#fullscreenBtn').click();await expect(page.locator('#waveStory')).toBeVisible();await page.locator('.cell[data-r="4"][data-c="3"]').click();const geo=await page.evaluate(()=>{const b=document.getElementById('board').getBoundingClientRect(),c=document.querySelector('.cards-panel').getBoundingClientRect();return{bottom:b.bottom,cards:c.top,width:b.width,h:b.height,w:innerWidth}});expect(geo.bottom).toBeLessThanOrEqual(geo.cards);expect(geo.width).toBeGreaterThan(geo.w*.8);expect(geo.h).toBeGreaterThan(60);await page.screenshot({path:info.outputPath('story-fullscreen.png')});await page.locator('#waveStorySkip').click();await expect(page.locator('#waveStory')).toBeHidden();expect(errors).toEqual([]);
});
